Assistant checkpoint: Fix Parcelable error by removing ViewModel from MainScreen
Assistant generated file changes:
- composeApp/src/commonMain/kotlin/com/healthanalytics/android/presentation/navigation/MainScreen.kt: Remove ViewModel from MainScreen constructor to fix Parcelable error, Inject HealthDataViewModel using Koin instead of constructor
- composeApp/src/commonMain/kotlin/com/healthanalytics/android/App.kt: Remove ViewModel parameter from MainScreen instantiation

---

User prompt:

Process: com.healthanalytics.android, PID: 18121
android.os.BadParcelableException: Parcelable encountered IOException writing serializable object (name = com.healthanalytics.android.presentation.navigation.MainScreen)
	at android.os.Parcel.writeSerializable(Parcel.java:2831)
	at android.os.Parcel.writeValue(Parcel.java:2597)
	at android.os.Parcel.writeValue(Parcel.java:2396)
	at android.os.Parcel.writeList(Parcel.java:1449)
	at android.os.Parcel.writeValue(Parcel.java:2540)
	at android.os.Parcel.writeValue(Parcel.java:2396)
	at android.os.Parcel.writeList(Parcel.java:1449)
	at android.os.Parcel.writeValue(Parcel.java:2540)
	at android.os.Parcel.writeValue(Parcel.java:2396)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1332)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)

Replit-Commit-Author: Assistant
Replit-Commit-Session-Id: 6f24203e-b0dd-430a-882c-fe5c81bc0e4c